<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="5" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-07T14:55:25 IST" name="Default suite" finished-at="2024-11-07T14:57:46 IST" duration-ms="140789">
    <groups>
    </groups>
    <test started-at="2024-11-07T14:55:25 IST" name="Default test" finished-at="2024-11-07T14:57:46 IST" duration-ms="140789">
      <class name="extender.Practise">
        <test-method is-config="true" signature="AppLaunch()[pri:0, instance:extender.Practise@418c5a9c]" started-at="2024-11-07T14:55:26 IST" name="AppLaunch" finished-at="2024-11-07T14:55:34 IST" duration-ms="8481" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AppLaunch -->
        <test-method signature="TC_01_userLogin()[pri:1, instance:extender.Practise@418c5a9c]" started-at="2024-11-07T14:55:34 IST" name="TC_01_userLogin" finished-at="2024-11-07T14:56:04 IST" duration-ms="29622" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_01_userLogin -->
        <test-method signature="TC_02_surveyDetailsSubmitting()[pri:2, instance:extender.Practise@418c5a9c]" started-at="2024-11-07T14:56:04 IST" name="TC_02_surveyDetailsSubmitting" finished-at="2024-11-07T14:56:17 IST" duration-ms="13119" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_02_surveyDetailsSubmitting -->
        <test-method signature="ExistingCreditBalance()[pri:3, instance:extender.Practise@418c5a9c]" started-at="2024-11-07T14:56:17 IST" name="ExistingCreditBalance" finished-at="2024-11-07T14:56:37 IST" duration-ms="19875" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ExistingCreditBalance -->
        <test-method signature="TC_04_toolUsingJourney()[pri:4, instance:extender.Practise@418c5a9c]" started-at="2024-11-07T14:56:37 IST" name="TC_04_toolUsingJourney" finished-at="2024-11-07T14:57:26 IST" duration-ms="49546" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_04_toolUsingJourney -->
        <test-method signature="creditBalanceAfterToolUse()[pri:5, instance:extender.Practise@418c5a9c]" started-at="2024-11-07T14:57:26 IST" name="creditBalanceAfterToolUse" finished-at="2024-11-07T14:57:46 IST" duration-ms="20091" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Credit did not increment as expected. expected [12] but found [10]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Credit did not increment as expected. expected [12] but found [10]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at extender.Practise.creditBalanceAfterToolUse(Practise.java:239)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- creditBalanceAfterToolUse -->
        <test-method signature="Max()[pri:6, instance:extender.Practise@418c5a9c]" started-at="2024-11-07T14:57:46 IST" name="Max" finished-at="2024-11-07T14:57:46 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Max -->
      </class> <!-- extender.Practise -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
